=== nedkuj-fsk/test-lv3/primjer4.dtd
<!ELEMENT syllabus (class+)>
<!ELEMENT class (name,teacher,demonstrator*,schedule)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT teacher (#PCDATA)>
<!ELEMENT demonstrator (#PCDATA)>
<!ELEMENT schedule (day,time)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT time (#PCDATA)>

=== nedkuj-fsk/test-lv3/primjer4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE syllabus SYSTEM "primjer4.dtd">
<syllabus>
    <class>
        <name>Web arhitekture</name>
        <teacher>dr. Muhamed Begović</teacher>
        <demonstrator>Nedim Kujrakovic</demonstrator>
        <schedule>
            <day>Monday</day>
            <time>10:00</time>
        </schedule>
    </class>
    <class>
        <name>Baze podataka</name>
        <teacher>doc. dr. Adnan Dželilhodžić</teacher>
        <schedule>
            <day>Monday</day>
            <time>17:00</time>
        </schedule>
    </class>
    <class>
        <name>Softversko inžinjerstvo II</name>
        <teacher>doc. dr. Adnan Dželilhodžić</teacher>
        <schedule>
            <day>Wednesday</day>
            <time>17:00</time>
        </schedule>
    </class>
</syllabus>
